volumes:
  mongodb_data:
    driver: local

networks:
  dev_nk:
    driver: bridge


services:

  actix-db:
    container_name: actix-db
    image: mongo:latest
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    restart: unless-stopped
    volumes:
      - ./db_setup.js:/docker-entrypoint-initdb.d/db_setup.js:ro
    networks:
      - dev_nk
    ports:
      - "27017:27017"


  actix-app:
    container_name: actix-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      actix-db:
        condition: service_healthy
    networks:
      - dev_nk
    ports:
      - "8080:8080"
